### ISSUE TITLE
Duplicate broker creation - Harvester 2.6.1

### ISSUE THREAD

**Issue by rmuellerjr** [Esri/geoportal-server-harvester#102]
I don't recall this being an issue with v2.6.0, but seeing an issue on "submit" which does not clear input box. If submit button hit multiple times, will create duplicate brokers.

![image](https://user-images.githubusercontent.com/8677397/56046219-c3f53e00-5d10-11e9-8005-19108a318f89.png)

**Comment by mhogeweg** [comment]
Since we released 2.6.4 since this happened, have you seen this behavior in the later releases? 

Could you share the full URL to the geoportal used in this case?

**Comment by mhogeweg** [comment]
closing this issue as we now have released [2.6.5](https://github.com/Esri/geoportal-server-harvester/releases/tag/v2.6.5) with a new UI.
