### ISSUE TITLE
Files not harvested to the geoportal

### ISSUE THREAD

**Issue by Durga07** [Esri/geoportal-server-harvester#119]
I tried harvesting the files from Arcgis online to the Geoportal 2.6.3 through the Harvester 2.6.3. In the home section, it is said that the task is 'completed' but the file is not harvested to the Geoportal.(I'm not using the local system on which geoportal is installed, I'm using my Personal Computer)
This is the exported data of the task performed:
{
  "name": "",
  "source": {
    "type": "AGP-IN",
    "label": "ArcgisonlineD",
    "properties": {
      "agp-host-url": "https://arcg.is/0GqLzP",
      "agp-folder-id": "Trail Geoportal",
      "cred-username": "Durga7",
      "cred-password": "zzzzz",
      "agp-emit-xml": "true",
      "agp-emit-xml-fmt": "DEFAULT",
      "agp-emit-json": "false",
      "agp-max-redirects": "5"
    },
    "keywords": [],
    "ref": "4bb5f339-0910-438f-9b19-6a7601ea1a4f"
  },
  "destinations": [
    {
      "action": {
        "type": "GPT",
        "label": "X",
        "properties": {
          "gpt-host-url": "http://49.207.9.178:8080/geoportal",
          "cred-username": "publisher",
          "cred-password": "zzzzz",
          "gpt-index": "",
          "gpt-cleanup": "true",
          "gpt-accept-xml": "false",
          "gpt-accept-json": "false",
          "gpt-translate-pdf": "false"
        },
        "keywords": [],
        "ref": "5cee0cbd-07cb-43fb-8f93-4ec404b26204"
      }
    }
  ],
  "keywords": [],
  "incremental": false,
  "ignoreRobotsTxt": false,
  "ref": "bc376995-ada1-4ac7-9bfe-3be9232c97d6"
}

**Comment by mhogeweg** [comment]
hi, the agp-host-url points to a webmap. you need to just point to the root ArcGIS Online URL as indicated in the sample below the input box for the URL.

**Comment by Durga07** [comment]
I tried it this way, the file is still not harvested. Is this correct?
![Harvester1](https://user-images.githubusercontent.com/68694781/89209492-031d6180-d5dc-11ea-98e0-71fae6efcb63.PNG)

**Comment by mhogeweg** [comment]
the URL should be https (we'll update the example in the next release). Is your account Durga7 an ArcGIS Online user account (not the geoportal account, right)

**Comment by Durga07** [comment]
Yes, Durga7 is Arcgis Online user account

**Comment by mhogeweg** [comment]
ah, one other thing. the Folder field is a reference to the folder in ArcGIS Online. To get the proper folder id (not the name), access your ArcGIS Online organization and then in your Content tab, select the folder in the list of folders on the left under 'My Content'. Then you will see the folder id in the URL as the `folder` parameter

**Comment by Durga07** [comment]
Is this it?
![Screenshot (267)](https://user-images.githubusercontent.com/68694781/89213384-a2455780-d5e2-11ea-9d75-e2cb3d703da4.png)

**Comment by mhogeweg** [comment]
yes, that would be the ID

**Comment by Durga07** [comment]
Hi, this is how it came. But I can't find this file in the Geoportal
![Harvester2](https://user-images.githubusercontent.com/68694781/89251140-e9a80400-d633-11ea-9214-9874bf713722.PNG)

**Comment by mhogeweg** [comment]
when you select the link of the id on the right what do you see?
also, can you check the harvester AND geoportal logs? some of the validation happens in the geoportal and not in the harvester.

**Comment by Durga07** [comment]
Hi, the id doesn't navigate me to anywhere

Log file of Harvester:
[hrv.2020-08-04.log](https://github.com/Esri/geoportal-server-harvester/files/5050740/hrv.2020-08-04.log)

**Comment by mhogeweg** [comment]
your geoportal URL is not correct. you provide port 8080 in combination with https protocol. use **http**://49.207.9.178:8080/geoportal instead

**Comment by Durga07** [comment]
Yes, the files are harvested to Geoportal.
But why can't I add this in the Map viewer
![Capture6(Add AO)](https://user-images.githubusercontent.com/68694781/89877096-3c0d9580-dbdd-11ea-845a-9ceaccaff470.PNG)

The XML file : http://49.207.9.178:8080/geoportal/rest/metadata/item/02ff69fc5afa473c8e50e7a72184cc2e/xml

**Comment by mhogeweg** [comment]
that is because the actual resource referenced in the xml is the portal map viewer _application_. Geoportal can currently only add _web services_ to a map.  It looks like your map included the dark grey canvas basemap and the transportation world map service on top of that. if you register that map service separately in your portal, then harvest into geoportal, you should be able to add it to the map.
