### ISSUE TITLE
geoportal harvester not working

### ISSUE THREAD

**Issue by fortemf** [Esri/geoportal-server-harvester#120]
Hello

I have deployed both geoportal and geoportal harvester 2.6.4 War files - the smoke test worked fine with geoportal but when trying harvester I got a blank web browser screen (see attached screen grabs). Can they both run on the same port? 

![geoportal](https://user-images.githubusercontent.com/8375849/89201427-1813d980-d577-11ea-822c-01cea48f960d.PNG)
![harvester](https://user-images.githubusercontent.com/8375849/89201440-1d712400-d577-11ea-9229-1e6cb55686e3.PNG)

This is my first deployment of geoportal so not sure If I'm overlooking something?

Any insight would be greatly appreciated.

Thanks for your time and for developing a great software tool - looking forward to setting up a portal to connect many to useful data resources.

**Comment by mhogeweg** [comment]
hi. yes, both are 'just' java webapps that can run in your java container (like Apache Tomcat). the fact that the harvester gives an http 500 response suggests your browser was actually able to make contact, but something else went wrong. check the Tomcat logs (assuming you use Tomcat) and the harvester log itself.

**Comment by fortemf** [comment]
Thanks for the quick reply!
After checking the log (attached) it seems I need to upgrade my java environment?

[localhost.2020-08-03.log](https://github.com/Esri/geoportal-server-harvester/files/5017102/localhost.2020-08-03.log)

Is that the way you would interpret?

**Comment by mhogeweg** [comment]
you got it!
