### ISSUE TITLE
Harvesting from CKAN-Demo

### ISSUE THREAD

**Issue by Durga07** [Esri/geoportal-server-harvester#129]
Hi,

I uploaded a file on the CKAN-Demo page and tried harvesting that particular file. But along with that file other files are also getting harvested
![Capture](https://user-images.githubusercontent.com/68694781/93960885-14325580-fd77-11ea-8cad-e6aee06ae1e6.PNG)
The URL given is : https://demo.ckan.org/dataset/demokml
I want to harvest only one file, is that possible?

**Comment by mhogeweg** [comment]
Hi. No, that is not possible via CKAN harvest. If you want to take only 1 file you’ll have to use the upload feature directly in geoportal. Alternatively you could download the metadata from the source CKAN and put it in a web accessible folder, sink, or UNC path that you then harvest

**Comment by Durga07** [comment]
Hi, 
I am using DKAN demo url (https://demo.getdkan.org/) in CKAN input broker, but I could not harvest the data. Is dkan url supported in that broker?

**Comment by mhogeweg** [comment]
no, DKAN is currently not supported for harvesting. You could write a simple script that uses the DKAN proprietary API and downloads the metadata to a local folder from where you could use the Geoportal Harvester to publish the metadata into your Geoportal Server Catalog.

**Comment by EttoreM** [comment]
Thank you, @mhogeweg !

Much appreciated!
