### ISSUE TITLE
Correction to Command Line Interface Wiki

### ISSUE THREAD

**Issue by jjosserand** [Esri/geoportal-server-harvester#132]
Type of the adaptors and their parameters:
Input adaptors:
WAF - web accessible folder,  
	"waf-host-url" - harvesting root URL  
	"waf-pattern" - pattern to filter harvested files (GLOB pattern syntax); default: **.xml  
	"cred-username" - user name (optional)  
	"cred-password" - user password (optional)  
CSW - Catalog **_Servoce_** for the Web  -- should be "Service"
	"csw-host-url" - CSW service URL  
	"csw-profile-id" - CSW profile id  
	"cred-username" - user name (optional)  
	"cred-password" - user password (optional)  
UNC - Uniform Naming Convention folder  
	"unc-root-folder" - root folder (must be accessible by the harvester)  
	"unc-pattern" - pattern to filter harvested files (GLOB pattern syntax); default: **.xml  
GPTSRC - Geoportal server 2.0  
	"gpt-host-url" - Geoportal server URL  
	"gpt-index" - name of the **_indes_** to harvest (optional)  -- should be "index"
	"cred-username" - user name  
	"cred-password" - user password  
AGS - ArcGIS server **_servoces_**  -- should be "services"
	"ags-host-url" - arcgis server host url (before rest/services)  
	"ags-enable-layers" - true to harvest layers from map service (default: false)  
AGP-IN - ArcGIS Portal (or arcgis online)  
	"agp-host-url" - ArcGIS portal host url (before sharing)  
	"agp-folder-id" -  folder id or folder name (optional)  
	"cred-username" - user name  
	"cred-password" - user password  
CKAN - CKAN  
	"ckan-host-url" - CKAN host URL  
	"ckan-apikey" - CKAN API key (optional)

**Comment by mhogeweg** [comment]
@pandzel some typos in the UI

**Comment by mhogeweg** [comment]
resolved. thanks!
