### ISSUE TITLE
Unable to execute ESRI’s Source Code for Geoportal Server harvester 2.6.4

### ISSUE THREAD

**Issue by Dineshr25** [Esri/geoportal-server-harvester#145]
Hi, 

We are facing issue with ESRI’s Source Code for Geoportal Server harvester 2.6.4. 

Attached is the document outlining the problem.

Thanks & Regards
Dinesh
[Geoportal Server Development Harvester.docx](https://github.com/Esri/geoportal-server-harvester/files/6257198/Geoportal.Server.Development.Harvester.docx)

**Comment by mhogeweg** [comment]
before diving into how to debug multi-project maven applications (such as the harvester), why is H2 not sufficient? the harvester uses this as the internal data store for brokers and tasks. it is not intended as a full-fledged relational database.

**Comment by pandzel** [comment]
My recommendation is to use AdoptOpenJDK 11 to compile and run Geoportal Harvester and Apache Tomcat 9.x as a web server. This is environment is described on our Wiki page at: https://github.com/Esri/geoportal-server-harvester/wiki/Installation-guide. Unfortunately, the front page of the Geoportal Harvester hasn't been updated - I've just corrected it.

When it comes to H2 database it is being used exclusively for the harvester purposes as an embedded database; think of it as a black box solution. No other database is currently supported.

**Comment by Dineshr25** [comment]
Thanks a lot. I am checking with suggested environment and get back to you in case of any further issues.

**Comment by Dineshr25** [comment]
[Geoportal server harvester 2.6.4.docx](https://github.com/Esri/geoportal-server-harvester/files/6293901/Geoportal.server.harvester.2.6.4.docx)
Hi I am yet facing problem.

Attached is the document outlining the problem.

Please suggest.

Thanks & Regards
Dinesh

**Comment by Dineshr25** [comment]
Hi Pandzel, appreciate if you can help us with this issue. Thank You for your time.

**Comment by pandzel** [comment]
What happens when you execute maven build CLI without Eclipse? Did you try running command:
`mvn package`
I see some errors associated with running test. If command given above fails try skipping tests running:
`mvn package -Dmaven.test.skip=true `

From the log attached it's quite possible it is all associated with Eclipse, although I have to admit I have absolutely no knowledge about Eclipse - simply put it I don't use at all (always preferred NetBeans). Perhaps you have a way to configure Eclipse in such a way it can skip tests as well.

Just before I posted that message I cloned harvester repository and run build on it (on Windows and Ubuntu via Docker) and in both cases it passed and produced artifact. What you are reporting is very odd.

**Comment by Dineshr25** [comment]
Dear Piotr,

Today, I want to run code of Geoportal Server Harvester 2.6.5 in NetBeans and Eclipse both. But, I am yet facing issue related to maven install. i.e. code is not giving error. Can you please suggest further.

Thanks & Regards
Dinesh

**Comment by pandzel** [comment]
@Dineshr25 I have not enough details to provide you with a  meaningful help. I sense you are having fundamental issues with your environment and that's something which would be entirely on you. That said, if you are maintaining multiple Java SDK's on your machine make sure you are using the right one, Check JAVA_HOME and PATH variables or so. Using NetBeans is extremely easy; you just open top level pom.xml. After that you may check in project options if the right Java SDK is selected. Keep in mind that NetBEans have capability to work either with a build in instance of maven or with external maven. Both should work fine, but if you are curious which I am using then I amusing an external one.

**Comment by Dineshr25** [comment]
Dear Piotr,

Thanks a lot for your continued support.
Now, its working fine in Netbeans IDE.

Regards
Dinesh
