### ISSUE TITLE
System Requirement for Geoportal Server Catalog and Harvester

### ISSUE THREAD

**Issue by pradkumar** [Esri/geoportal-server-harvester#158]
Hi, 

Appreciate if someone point me to the system requirement page of Geoportal Server Catalog and Harvester v.2.4.

Specifically looking for operating system support, similar to below link of version 1.2.2.

https://github.com/Esri/geoportal-server/wiki/Preinstallation-1.2.2

Regards,
Pradeep

**Comment by mhogeweg** [comment]
hi Pradeep,

please see these pages:
- https://github.com/Esri/geoportal-server-harvester/wiki/Installation-guide
- https://github.com/Esri/geoportal-server-catalog/wiki/Installing-Geoportal-Server-2.6.4

**Comment by pradkumar** [comment]
Thank You Marten, 

Since there is no direct reference to the supported Operating system, I understand that the underlying OS of the supported prerequisite will work. 

Regards,
Pradeep

**Comment by mhogeweg** [comment]
that's correct

**Comment by pradkumar** [comment]
Thank Marten,

Appreciate your quick response.

Regards,
Pradeep
