### ISSUE TITLE
output to folder cleanup too agressive

### ISSUE THREAD

**Issue by valentinedwv** [Esri/geoportal-server-harvester#16]
The output to folder puts items in folders
so if I say /opt/tomcat/webapps/metadata

for a run for against an service an items put into 
/opt/tomcat/webapps/metadata/opentopo.sdsc.edu/
which is the base name of the host.

If I set perform cleanup, it zaps all items in metadata, and not just the host folder.

Option 1: just clean up folder when items will be placed
option 2: use input broker name

**Comment by pandzel** [comment]
Could you get latest code and try again, please. It works for me now, but I wanted to make sure it also works in your environment.
