### ISSUE TITLE
HTTP ERROR 500 when accessing http://localhost:8080/harvester

### ISSUE THREAD

**Issue by raibrahim** [Esri/geoportal-server-harvester#176]
I have installed AdoptOpenJDK 11, Tomcat 9.0.29 and ElasticSearch 7.5.0 in my local computer and deployed the harvester.war file inside the C:\Program Files\Apache Software Foundation\Tomcat 9.0\webapps folder. But when I tried to access the http://localhost:8080/harvester from my browser, i got HTTP ERROR 500.

**Comment by mhogeweg** [comment]
hi. are you able to access the Tomcat landing page http://localhost:8080 itself? what details of the error do you see in the Tomcat or harvester log files? by default these will all be in the Tomcat logs folder.

**Comment by raibrahim** [comment]
> hi. are you able to access the Tomcat landing page http://localhost:8080 itself? what details of the error do you see in the Tomcat or harvester log files? by default these will all be in the Tomcat logs folder.

Thanks for reply @mhogeweg 
I have checked the log files, and found this: "com/esri/geoportal/harvester/rest/BrokerController has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0". It seems i have mistakenly set the Java Path to the older version when installing the Tomcat. Sorry for my mistake.
