### ISSUE TITLE
Failed to remove task/execute task

### ISSUE THREAD

**Issue by tom62291** [Esri/geoportal-server-harvester#178]
![image](https://user-images.githubusercontent.com/8196925/147719850-3906271d-62f7-407d-8dad-58b5ef9a2538.png)

Hello, I have change the config point to a postgresql and place the jdbc postgresql jar in lib folder.
I can succesfully add/edit/delete brokers.
I can succesfully create task.

However, I cannot execute task or remove the task.
Please help.

![image](https://user-images.githubusercontent.com/8196925/147719919-69d93079-9a12-41b2-b44e-86ba8b656341.png)

**Comment by mhogeweg** [comment]
do you get messages in the harvester log when trying to remove the task? or else in the browser console/network responses?

**Comment by tom62291** [comment]
Hi, there is no special log message from the network response or even the log file

Attached my log config, log output and network response.

![image](https://user-images.githubusercontent.com/8196925/147720164-5642e847-f484-423b-ab3e-ff8ad8cc677d.png)
![image](https://user-images.githubusercontent.com/8196925/147720204-48fbf6f9-21e7-493c-80fe-e94623bb4c98.png)
![image](https://user-images.githubusercontent.com/8196925/147720239-60d34806-1d75-4934-8869-b9a2ef37ba17.png)
![image](https://user-images.githubusercontent.com/8196925/147720248-a954291b-8b62-43fd-8b36-150b7f127a53.png)

**Comment by tom62291** [comment]
Hi, finally, I found that postgresql does not support CLOB and some table and index are failed to create.

I have create the domain for clob
```create domain clob as text;```

and then recreate all missing table and index.

**Comment by tom62291** [comment]
Hello, I just find CLOB is not support in PostgreSQL.
Any guideline for user if we want to use PostgreSQL?

**Comment by mhogeweg** [comment]
oh wait, are you trying to make postgresql the database where harvester stores the brokers/task information? That is an untested configuration. I thought you were trying harvest from PostgreSQL.

**Comment by tom62291** [comment]
yes
