### ISSUE TITLE
Translation for AGOL/Portal

### ISSUE THREAD

**Issue by davidmccorkindale** [Esri/geoportal-server-harvester#198]
Hi,

Is there a timeframe for the next release when the changes made in commit https://github.com/Esri/geoportal-server-harvester/commit/78d5575cb086407de418bf5e1bb2e33f9821c475 to enable translation of metadata to ArcGIS might become available?

Thanks.

David

**Comment by mhogeweg** [comment]
We are working on a release of the Catalog application currently. After that, we will work on a release of the harvester. You may build the app from the source code directly to get access to this particular feature.
