### ISSUE TITLE
Automatically harvest upon detected changes or new XML

### ISSUE THREAD

**Issue by MapZombie** [Esri/geoportal-server-harvester#20]
Automating the process of harvesting would be great. Would it be possible to connect harvester to a script that detects and changes in the folder?  

For example if a **new XML file is added to a harvested folder it would automatically detect it and begin harvesting.**

**Comment by pandzel** [comment]
Yes (but it's not there yet). The basic idea is that scheduling is also a broader concept based on triggers paradigm. One type of the trigger is such an object which starts harvesting according to the elapsed time (as available now). Another is a listener to the changes of the observed folder; once the content of the folder has changed it starts harvesting. Java has already everything to implement such an observer so implementing trigger wouldn't be that hard.

**Comment by MapZombie** [comment]
That's great to hear!  Any hints on when an folder observer trigger would be implemented?  

If it is quite a bit down the line would you be able to point me to which files would need to be changed with Java so that I could try this in our environment?  Thanks.

**Comment by pandzel** [comment]
Latest release of the Harvester has a "Sink" input broker. This input broker allows to declare a designated folder to be a drop folder where harvester will observer and listen to any new items in it. When combined into a task it allows to publish any xml metadata into the output broker. To get it working, a task must be started (this task is a perpetual task; it stays active until an operator cancels it). A metadata could be dragged and dropped into that folder (or copied); after publishing into the destination, metadata will be deleted from the sink.
