### ISSUE TITLE
Upgrading to 2.7 issue 

### ISSUE THREAD

**Issue by grundlinghd** [Esri/geoportal-server-harvester#202]
Hi team, 

We have upgraded the harvester to 2.7 by replacing our WAR file in apache tomcat on our secure server and local test environment. Also tested generating our own WAR file using the master branch. 

The harvester application does launch however we are getting an error on the top right 'Unable to access tasks information' (screenshot attached) . The harvester logs are clean, however our tomcat9-stderr logs (Attached logs) are displaying 
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: General error: "The write format 1 is smaller than the supported format 2 [2.1.210/5]" [50000-210]

We have been using 2.6.5 without issue. Any advise is appreciated. 

Thanks,
Daniel 
![2 7_harvester_error](https://github.com/Esri/geoportal-server-harvester/assets/116318580/86cb5724-c2c3-440c-b041-3358580e8ff5)
 
[tomcat9-stderr.2023-06-21.log](https://github.com/Esri/geoportal-server-harvester/files/11808081/tomcat9-stderr.2023-06-21.log)

**Comment by mhogeweg** [comment]
hi, this is due to the internal h2 database (used to store the broker and task definitions) being upgraded in 2.7.0. Please set a different location for the h2 database by updating `jdbc.url` in /harvester/WEB-INF/classes/config/hrv.properties.

for example: `jdbc.url=jdbc:h2:~/harvester_270`

**Comment by grundlinghd** [comment]
Thank you Marten, this is resolved now.
