### ISSUE TITLE
Enable ArcGIS Online/Portal authentication in the harvester

### ISSUE THREAD

**Issue by mhogeweg** [Esri/geoportal-server-harvester#205]
the harvester currently has simple and LDAP authentication options. This enhancement would allow ArcGIS Online/Enterprise authentication.

**Comment by davidmccorkindale** [comment]
This would be great to have to streamline the authentication inline with geoportal.

**Comment by as0050629** [comment]
@mhogeweg https://github.com/Esri/geoportal-server-harvester/pull/218
