### ISSUE TITLE
tasks panel Sort

### ISSUE THREAD

**Issue by valentinedwv** [Esri/geoportal-server-harvester#22]
Minor improvement to the UI
* Order by source
* Order by output

**Comment by pandzel** [comment]
I am more interested in what kind of "real life" issue you are dealing with?
Is your request concerning tasks list, brokers list, processes?

**Comment by valentinedwv** [comment]
We want to harvest to a folder, reprocess/enhance, then push enhanced records to GPT.

Brokers and Tasks.
Right now 27 "Brokers", and 37 tasks. (some brokers route to a folder and others to a GPT2.x). Sorting brokers just makes them easier to find.

I'd like the tasks grouped by source... which is order by source.

Some of this is development cruft. I'm sure a broker which pulls, enhances and publishes will be done at some point, or the enhancement services will push directly to GPT.

**Comment by pandzel** [comment]
Pull request [#71](https://github.com/Esri/geoportal-server-harvester/pull/71) gives ability to group tasks by input source. All tasks are sorted by name within each group. User has ability to name each task individually during its creation.
