### ISSUE TITLE
translate locale information when harvesting to ArcGIS Online/Portal

### ISSUE THREAD

**Issue by mhogeweg** [Esri/geoportal-server-harvester#220]
when translating XML to ArcGIS XML as part of harvesting from a source to ArcGIS Online/Portal, the localized strings for title/abstract do not get generated into ArcGIS XML.

this requires an update to ...\geoportal-server-harvester\geoportal-commons\geoportal-commons-meta\src\main\resources\meta\ISO19139_to_ArcGIS.xsl

**Comment by mhogeweg** [comment]
resolved in branch 2.7.2_220

**Comment by as0050629** [comment]
Completed in 2.7.2
