### ISSUE TITLE
Enable query on harvest source

### ISSUE THREAD

**Issue by smrgeoinfo** [Esri/geoportal-server-harvester#31]
It would be useful to allow specification of a CQL or OGC Filter Query to filter a subset of records for harvesting from a CSW broker.   For instance in my case I'd like to harvest only records from the GCMD catalog at https://cmr.earthdata.nasa.gov/csw/collections with a filter &CONSTRAINTLANGUAGE=CQL_TEXT&constraint=AnyText=*NSF?PLR*

**Comment by mhogeweg** [comment]
We do not have plans to build this into the harvester. Instead, you can create a CSW profile and include this into the CSW client (geoportal-commons-csw-client). In it you would update the ```CSW_2.0.2_APISO_NASA_GetRecords_Request.xslt``` transformation to add the specific query. You would then select the new 'broker with filter' when registering the source CSW.
