### ISSUE TITLE
Provide a compiled war file

### ISSUE THREAD

**Issue by mgg-eagle** [Esri/geoportal-server-harvester#4]
Hi,

You have a downloadable .war file for the catalog app, can you please provide one for the harvester for those of us unable to compile our own.

Thanks,
Marc

**Comment by pandzel** [comment]
Harvester 2.0 has not been released yet and it's code is still a subject to the daily significant changes. Once we stabilize a release it's code, be sure that all the artifacts including WAR web application will be available for download.

**Comment by MapZombie** [comment]
Hey guys nice work so far, just curious as to the timeline of the first release for harvester?

**Comment by rafteryd** [comment]
Hi, 

I'd also like to check on the release date for the .war file? The documentation suggests it exists?

Thanks,

D

**Comment by pandzel** [comment]
Latest release available from: [https://github.com/Esri/geoportal-server-harvester/releases](https://github.com/Esri/geoportal-server-harvester/releases)
