### ISSUE TITLE
scheduler not working

### ISSUE THREAD

**Issue by smrgeoinfo** [Esri/geoportal-server-harvester#44]
I'm trying to set a schedule for harvest jobs, using harvester release 2.5.1. I've set up several tasks, and I want to schedule them. I'm working with a new VM, CentOS 7.3., geoportal 2.5.0 runnign on same machine.  SELunix is set to permissive. Harvesting works when I run the tasks (the input brokers are WAF, Output is localhost geoportal).
When I click on 'schedule' a little modal dialog opens with titled 'Task', with a 'Type' combo box and a 'Submit' button. The menu in the 'Type' combo box is empty. Clicking submit does nothing.
In the hrvyyy-mm-dd.log file, I see this message that appears to be related to trying to schedule: 

> ... SEVERE [http-nio-8080-exec-1] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [spring] in context with path [/harvester] threw exception [Request processing failed; nested exception is java.util.MissingResourceException: Can't find bundle for base name EngineResource, locale en_US] with root cause
> ...
> 	at com.esri.geoportal.harvester.engine.triggers.AtTrigger.getTemplate(AtTrigger.java:95

)

**Comment by pandzel** [comment]
Indeed, EngineResource.properties file has been missing. Latest commit fixes that.

**Comment by smrgeoinfo** [comment]
I can't get a workable war to build in Eclipse (still a newbie), so I just want to copy the EngineResource.properties onto the server webapps/harvester folder, but its not clear what path it should be at. Where does this properties file belong?
