### ISSUE TITLE
Request:  Scheduled harvesting

### ISSUE THREAD

**Issue by MapZombie** [Esri/geoportal-server-harvester#5]
It would be great to have the same functionality as the previous version in terms of scheduling harvests.  As well as the feature to have only new/updated metadata get harvested.

**Comment by pandzel** [comment]
Current harvester design goes way beyond that; there is a "trigger" concept which allows to create any type of entities which would start up harvesting process. One type is a temporal trigger which does scheduled type triggering. Another type of trigger might be a trigger which observes a local folder - once a metadata is being dropped into that folder, it triggers harvesting of that folder. Yet another would be a a trigger which activates harvesting once a particular message arrives through the message queue (JMS).

Current implementation has full potentials available through REST interface (there is no UI yet). More types of triggers will arrive with the subsequent releases.

It is worth mentioning that you are not limited to scheduling through build-in scheduler; it is possible to schedule through Linux (Unix) crontab mechanism or Microsoft Windows task scheduler.

One may say: the sky is a limit...
