### ISSUE TITLE
Is the harvester able to handle federated logins to ArcGIS Online?

### ISSUE THREAD

**Issue by andrewrudin-austin** [Esri/geoportal-server-harvester#51]
I'm trying to setup a broker to grab items within our ArcGIS Online org.  We have ArcGIS Online federated with our Active Directory.  I'm giving my broker the root of our AGOL org http://austin.maps.arcgis.com and then putting in my federated email and password (at the moment I'm just testing, so my own login is okay).  The task fails when using this broker.  

My goal is to harvest just the items that are in our org AND have been shared with the entire org.  Not sure if that filtering is possible with the harvester yet.

Thank you,

**Comment by pandzel** [comment]
Such scenario has never been tested, so what you are describing might be a real issue. Is there a log from that event?

**Comment by andrewrudin-austin** [comment]
Here is what is in the hrv. log after I use an input broker with my federated account.

18-Apr-2018 09:33:44.902 INFO [http-nio-8080-exec-2] com.esri.geoportal.harvester.engine.defaults.DefaultProcessor.createProcess SUBMITTING: PROCESSOR: DEFAULT[], SOURCE: AGP-IN[agp-host-url=http://austin.maps.arcgis.com, agp-folder-id=, cred-username=andrew.rudin@austintexas.gov, cred-password=*****, agp-emit-xml=true, agp-emit-json=false], DESTINATIONS: [GPT[gpt-host-url=http://coaagssocdev1.coacd.org:8080/geoportal, cred-username=gptadmin, cred-password=*****, gpt-index=, gpt-cleanup=false, gpt-accept-xml=true, gpt-accept-json=false]], INCREMENTAL: false, IGNOREROBOTSTXT: true
18-Apr-2018 09:33:44.902 INFO [HARVESTING] com.esri.geoportal.harvester.engine.defaults.DefaultProcessor$DefaultProcess.lambda$new$1 Started harvest: PROCESSOR: DEFAULT[], SOURCE: AGP-IN[agp-host-url=http://austin.maps.arcgis.com, agp-folder-id=, cred-username=andrew.rudin@austintexas.gov, cred-password=*****, agp-emit-xml=true, agp-emit-json=false], DESTINATIONS: [GPT[gpt-host-url=http://coaagssocdev1.coacd.org:8080/geoportal, cred-username=gptadmin, cred-password=*****, gpt-index=, gpt-cleanup=false, gpt-accept-xml=true, gpt-accept-json=false]], INCREMENTAL: false, IGNOREROBOTSTXT: true
18-Apr-2018 09:33:44.917 INFO [HARVESTING] com.esri.geoportal.harvester.support.ReportLogger.started Started processing task: PROCESS:: status: working, title: PROCESSOR: DEFAULT[], SOURCE: AGP-IN[agp-host-url=http://austin.maps.arcgis.com, cred-username=andrew.rudin@austintexas.gov, cred-password=*****, agp-emit-xml=true, agp-emit-json=false], DESTINATIONS: [GPT[gpt-host-url=http://coaagssocdev1.coacd.org:8080/geoportal, cred-username=gptadmin, cred-password=*****, gpt-index=, gpt-cleanup=false, gpt-accept-xml=true, gpt-accept-json=false]], INCREMENTAL: false, IGNOREROBOTSTXT: true
18-Apr-2018 09:33:44.917 INFO [HARVESTING] com.esri.geoportal.harvester.support.ReportStatistics.started Harvesting of PROCESS:: status: working, title: PROCESSOR: DEFAULT[], SOURCE: AGP-IN[agp-host-url=http://austin.maps.arcgis.com, cred-username=andrew.rudin@austintexas.gov, cred-password=*****, agp-emit-xml=true, agp-emit-json=false], DESTINATIONS: [GPT[gpt-host-url=http://coaagssocdev1.coacd.org:8080/geoportal, cred-username=gptadmin, cred-password=*****, gpt-index=, gpt-cleanup=false, gpt-accept-xml=true, gpt-accept-json=false]], INCREMENTAL: false, IGNOREROBOTSTXT: true started at Wed Apr 18 09:33:44 CDT 2018
18-Apr-2018 09:33:45.230 INFO [HARVESTING] com.esri.geoportal.harvester.support.ReportLogger.completed Completed processing task: PROCESS:: status: completed, title: PROCESSOR: DEFAULT[], SOURCE: AGP-IN[agp-host-url=http://austin.maps.arcgis.com, cred-username=andrew.rudin@austintexas.gov, cred-password=*****, agp-emit-xml=true, agp-emit-json=false], DESTINATIONS: [GPT[gpt-host-url=http://coaagssocdev1.coacd.org:8080/geoportal, cred-username=gptadmin, cred-password=*****, gpt-index=, gpt-cleanup=false, gpt-accept-xml=true, gpt-accept-json=false]], INCREMENTAL: false, IGNOREROBOTSTXT: true
18-Apr-2018 09:33:45.230 INFO [HARVESTING] com.esri.geoportal.harvester.support.ReportStatistics.completed Harvesting of PROCESS:: status: completed, title: PROCESSOR: DEFAULT[], SOURCE: AGP-IN[agp-host-url=http://austin.maps.arcgis.com, cred-username=andrew.rudin@austintexas.gov, cred-password=*****, agp-emit-xml=true, agp-emit-json=false], DESTINATIONS: [GPT[gpt-host-url=http://coaagssocdev1.coacd.org:8080/geoportal, cred-username=gptadmin, cred-password=*****, gpt-index=, gpt-cleanup=false, gpt-accept-xml=true, gpt-accept-json=false]], INCREMENTAL: false, IGNOREROBOTSTXT: true completed at Wed Apr 18 09:33:45 CDT 2018. No. succeded: 0, no. failed: 0
