### ISSUE TITLE
Set Contributor

### ISSUE THREAD

**Issue by valentinedwv** [Esri/geoportal-server-harvester#75]
Allow for the setting of a contributor in the harvest source

**Comment by pandzel** [comment]
Could you elaborate more on that request, please.

**Comment by mhogeweg** [comment]
@valentinedwv  would this contributor be a contact person that should show up in the geoportal catalog that the source is harvester into?

**Comment by valentinedwv** [comment]
Old thought... We have one "user" whom does the GPT harvesting, it would prevent everything from being gptadmin the only 'owner' in a geoportal.

**Comment by mhogeweg** [comment]
in the facets you can have the harvest source 'Source of Origin' (I don't like this title for it, but that's a different story). http://geoss.esri.com/geoportal2/#searchPanel it's the bottom facet. I'll go ahead and close this ticket.
