### ISSUE TITLE
OAI PMH do not send empty set

### ISSUE THREAD

**Issue by valentinedwv** [Esri/geoportal-server-harvester#77]
fails
https://mercury.ornl.gov/oai/provider?verb=ListIdentifiers&metadataPrefix=fgdc&set=
works
https://mercury.ornl.gov/oai/provider?verb=ListIdentifiers&metadataPrefix=fgdc
if set is empty, do not send.

**Comment by pandzel** [comment]
Fixed with [https://github.com/Esri/geoportal-server-harvester/commit/23f3cdc3f1e404342bd73d70c60635558453ad16](https://github.com/Esri/geoportal-server-harvester/commit/23f3cdc3f1e404342bd73d70c60635558453ad16) changeset.
