### ISSUE TITLE
OAI not stopping

### ISSUE THREAD

**Issue by valentinedwv** [Esri/geoportal-server-harvester#79]
Collecting data from DLESE
http://uc.dls.ucar.edu/dds_oai_server/services/oaiDataProvider/oai_explorer.jsp

this says 7316 records
http://uc.dls.ucar.edu/oai?verb=ListIdentifiers&metadataPrefix=gmd

Server count now at 300k, even though entire site only has 36k records
http://uc.dls.ucar.edu/oai?verb=ListRecords&metadataPrefix=oai_dc

**Comment by valentinedwv** [comment]
![image](https://user-images.githubusercontent.com/851784/41434966-439585c0-6fd2-11e8-937b-81bb3668ed90.png)

not really sure what is going on. Maybe the DLESE server?

**Comment by valentinedwv** [comment]
The Mercury OAI has no resumption token, and 271 records.
Does not stop.

https://mercury.ornl.gov/oai/provider?verb=ListIdentifiers&metadataPrefix=fgdc

https://mercury.ornl.gov/oai/oaisearch.do

**Comment by valentinedwv** [comment]
[OAI.patch.txt](https://github.com/Esri/geoportal-server-harvester/files/2104350/OAI.patch.txt)
patch

**Comment by pandzel** [comment]
Patch applied with https://github.com/Esri/geoportal-server-harvester/commit/40cdc65aa34a576d79be86bf64501317530e9813

**Comment by pandzel** [comment]
Verified.
