### ISSUE TITLE
Task>Run not working

### ISSUE THREAD

**Issue by valentinedwv** [Esri/geoportal-server-harvester#8]
Pulled the latest master
Task>Run not working

Have scheduled some.

**Comment by pandzel** [comment]
"Run" command works for me. Scheduling is in development.

**Comment by valentinedwv** [comment]
I'm not seeing anything show up the processes list or in the history link

**Comment by valentinedwv** [comment]
Resolved:
Removed the old harvester.mv.db and restarted.
