### ISSUE TITLE
Geoportal 2.6 Migration Tool only gets registration records

### ISSUE THREAD

**Issue by rmbradley** [Esri/geoportal-server-harvester#84]
Hi,
I'm trying to migrate Geoportal 1.2.9 metadata backed by a SQL Server 2012 database to a Geoportal 2.6 instance.  I'm pretty sure I got the context.xml configured correctly with the right parameters because I get all the registration records from the database, but no actual metadata.  Is this correct behavior and I have to subsequently use each registration input broker to finally get all the metadata?

Thanks,

Rick

**Comment by pandzel** [comment]
That's correct. Current implementation of the migration tool will only import metadata which has not been acquired through harvesting.
